### PR TITLE
Litex add litespi flash and watchdog

### PR DESCRIPTION
**Pull request by maass-hamburg**
- Be able to use spi flash from LiteSPI.
- Adds watchdog

### CODE REVIEW

**Comment by maass-hamburg** [comment]
Fixed the ci and updated the it to use https://github.com/YosysHQ/oss-cad-suite-build, which contains yosys, prjoxide and nextpnr, so we don't have to compile and install it our self.

**Comment by maass-hamburg** [comment]
@enjoy-digital @tgorochowik you might want to take a look

**Review by tgorochowik — COMMENTED** [review]
Looks reasonable, thanks! I assume you verified it on hardware?

**Comment by maass-hamburg** [comment]
@tgorochowik I tested it successful on my arty

**Review by tgorochowik — APPROVED** [review]

**Pull request merged**
